### ISSUE TITLE
安卓编译通不过??

### ISSUE THREAD

**Issue by darkfiredarkhalo** [shimohq/react-native-x5#4]
warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.tencent.smtt.sdk.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.
这个警告一直都在....
最后是这个错误:
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define LMTT/ThirdAppInfoNew;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define LMTT/ThirdAppInfoNew;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:react-native-x5:transformClassesWithDexForDebugAndroidTest FAILED

Execution failed for task ':react-native-x5:transformClassesWithDexForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by HaoyCn** [comment]
同遇到这个问题, 除了说明文档的步骤外, 按如下操作后可以正常编译, `WebView.getX5CoreVersion` 能取到值, 不过我测试机上还是看不到标志性的水滴效果.

1. 删除 ./android/app/build 文件夹
2. 打开 ./android/app/build.gradle 在 `defaultConfig` 中添加 `multiDexEnabled = true`
3. 打开 react-native-x5 的 NPM 包中的 ./index.android.js, 删除第三行, 第二行修改为 `import { WebView, NativeModules, requireNativeComponent } from 'react-native';`
4. 命令行打开 ./android 目录, 运行 `gradlew clean` (编译失败就运行这个)

除此之外, 可能还需要用管理员身份运行命令行.

祝好运!

**Comment by Jungley8** [comment]
"react": "16.0.0-alpha.12",
"react-native": "0.48.3",

@HaoyCn  按你的方法 还是报错
